
// export const VOTER_VERIFY_START = 'VOTER_VERIFY_START';

// export const VOTER_VERIFY_END = 'VOTER_VERIFY_END';

// export const VOTER_SUBMISSION_START = 'VOTER_SUBMISSION_START';

export const VOTER_SUBMISSION_END = 'VOTER_SUBMISSION_END';
